### ISSUE TITLE
Highlight APs with PMKID and possible export the PMKID file

### ISSUE THREAD

**Issue by DaniloNC** [kismetwireless/kismet#101]
PMKID cracking are supported on both hashcat and john jumbo and is described in this post: https://hashcat.net/forum/thread-7717.html

It would be nice if Kismet could highlight networks with PMKID (Similar to the 4-way handshake highlight) and also be able to export the pcap and the hashcat mode 16800 file for that network.

**Comment by ZeroChaos-** [comment]
please please please, pretty please

**Comment by kismetwireless** [comment]
Pcap export is now supported for them in git
