### ISSUE TITLE
Precision of avg. coordinates

### ISSUE THREAD

**Issue by dreadnought** [kismetwireless/kismet#105]
Hi,
I notices that the avg. coordinates (kismet.common.location.avg_loc) are less precise than the others (4 vs. 6 digits), which seems to come from the `precision_multiplier` constant in [tracked_location.h](https://github.com/kismetwireless/kismet/blob/master/tracked_location.h#L103).

Is there a reason for that? When plotting all networks to a map, it leads to a grid where a lot of them are grouped on a single position.

**Comment by kismetwireless** [comment]
Fair; just increased it and pushed.
