### ISSUE TITLE
Tag a version for a macOS Homebrew release

### ISSUE THREAD

**Issue by wrobelda** [kismetwireless/kismet#106]
Hi,

I am about to send a pull request for Homebrew to include the kismet formula in the official branch. They require an actual release (as opposed to git HEAD) to be used for source code, and the most recent kismet-2018-08-beta1 release does not build under macOS (https://github.com/kismetwireless/kismet/issues/80).

Any chance you tag a new beta release, please?

**Comment by kismetwireless** [comment]
There will be a beta two at some point in the coming days or weeks, yes.

Beta 1 should compile fine, however

**Comment by wrobelda** [comment]
> Beta 1 should compile fine, however

In that issue I referenced you say yourself that "The solution is to use the git-master code which does not include references to native thread handles (and hasn't since early august)".
