### ISSUE TITLE
REST exception

### ISSUE THREAD

**Issue by flightxar** [kismetwireless/kismet#110]
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('*KISMET: 0.0.0 1549166623 \x01zero\x01 \x01netxml,nettxt,gpsxml,alert\x01 0 \n',))

Python 2.7.15rc1
Ubuntu 18.04.1 LTS

**Comment by kismetwireless** [comment]
The kismetrest api only works against modern kismet (beta or git); you're pointing it at an old non-http-based Kismet version.
