### ISSUE TITLE
Documentation regarding log rollover in kismet_logging.conf

### ISSUE THREAD

**Issue by mrmegaloler** [kismetwireless/kismet#111]
The kismet_logging.conf file states that "Additionally, Kismet log files can be limited in duration, and
# automatically rolled to new files.", however it does not provide documentation for doing so.

What is the proper method of achieving this functionality?

Looking forward to your answer!

**Comment by kismetwireless** [comment]
There is no support for this in the current logging architecture; the comment has been removed.
