### ISSUE TITLE
WiGLE CSV export - minor date format issue

### ISSUE THREAD

**Issue by rksh** [kismetwireless/kismet#122]
It appears that the timestamps in WiGLE.net CSV exports are being written with month abbreviations instead of month numbers in the time column, e.g.:
`2019-Mar-04 12:41:26`
instead of
`2019-03-04 12:41:26`

reference at:
https://wigle.net/phpbb/viewtopic.php?f=3&t=2627&p=10034#p10034

consequence: missing observation timestamps in export format
severity: low

proposed fix follows.

**Comment by kismetwireless** [comment]
Merged in, just cleaning up original issue report
