### ISSUE TITLE
kali apt repository: "expected kali but got rolling"

### ISSUE THREAD

**Issue by TechInterMezzo** [kismetwireless/kismet#132]
I get the following error when I try to install kismet with apt on raspberry pi kali.

`W: Conflicting distribution: https://www.kismetwireless.net/repos/apt/release/kali kali InRelease (expected kali but got rolling)`

If I look directly at https://www.kismetwireless.net/repos/apt/release/kali/dists/kali/InRelease,
it says "Codename: rolling" at line 6.

The expected name would be kali instead of rolling.

**Comment by kismetwireless** [comment]
Change your apt line to 'rolling' for the releases repo for now; it will be
replaced with 'kali' with the next release build when beta3 comes out,
however.

**Comment by kismetwireless** [comment]
I'll work on rebuilding the release repos tonight maybe which will likely
make the error go away anyhow

**Comment by kismetwireless** [comment]
The release repos are now rebuild with aptly, which changed some things;
should now match the codename 'kali'

**Comment by dragorn** [comment]
You may need to pull the nightly repos depending on your kali version
still; kali recently swapped some libraries and upgraded them & those
aren't in the beta2 builds.  beta3 is relatively immanent though.
