### ISSUE TITLE
Raspberry Pi 3 Kismet on Kali Full Install Failing Make

### ISSUE THREAD

**Issue by Nailar** [kismetwireless/kismet#143]
Compiling on a Raspberry Pi 3 Model B+, new 16GB micro SD card, 1GB external USB swapfile,  Kali Linux RPi install with a Kali-Linux-Full upgrade, and following directions @  https://www.kismetwireless.net/docs/readme/quickstart/

Configuration complete:
         Compiling for: linux-gnueabi (armv7l)
           C++ Library: stdc++
   Installing as group: root
       Installing into: /usr/local
          Setuid group: kismet
   Linux WEXT capture : yes
        Prelude  SIEM : no
   PCRE Regex Filters : yes
          pcap capture: yes
       airpcap control: n/a (only Cygwin/Win32)
        PPI log format: yes
LibCapability (enhanced
   privilege dropping): yes
   OSX/Darwin capture : n/a (only OSX/Darwin)
         Linux Netlink: yes (mac80211 VAP creation) - libnl-3.0 libnl-genl-3.0
  Linux NetworkManager: yes (libnm NetworkManager control)
       Linux Bluetooth: yes
         nRF MOuseJack: yes
        Python Modules: yes
       RTL-SDR RTL_433: yes
       RTL-SDR RTLAMR: yes
      RTL-SDR RTLADSB: yes
      Freaklabs Zigbee: yes
 lm-sensors monitoring: yes
        Built-in Debug: yes - Full debug info available on crash, using unwind

But when I make I get the following error;
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [Makefile:588: datasourcetracker.cc.o] Error 1
make: *** Waiting for unfinished jobs.

I ran another git pull and am not seeing this file in my kismet directory, is this something I can just touch?

**Comment by Nailar** [comment]
kismetwireless thanks for the suggestion. I increased my swapfile to 3G and ran make again without the -j option and it worked great. Now to configure it :)

**Comment by eren12331** [comment]
and how exactly do you pre-build rpi-packages? should i use a vm for that maybe?

**Comment by kismetwireless** [comment]
Packages for several rpi distros are available from the kismet download
page.

Otherwise - yes - building either in a cross-compiling environment or under
an emulated system using qemu/systemd-nspawn/docker+qemu is the way to go;
the *runtime* requirements for Kismet are quite modest, but gcc and clang
both need a huge amount of ram for compiling.
