### ISSUE TITLE
Not able to start interface over command line (-c)

### ISSUE THREAD

**Issue by JK2210** [kismetwireless/kismet#157]
When I try to start kismet with a specific interface (`kismet -c source:wlan1`) I get an error:

```
ERROR: Unable to find driver for 'source:wlan1'.  Make sure that any 
       required plugins are loaded, the interface is available, and any 
       required Kismet helper packages are installed.
ERROR: Data source 'source:wlan1' failed to launch: Unable to find driver 
       for 'source:wlan1'.  Make sure that any required plugins are 
       loaded, the interface is available, and any required Kismet helper 
       packages are installed.
```
But when I start the interface over the web UI it works great.

I am using Kismet 2019-05-02 on a current raspbian.

Do you have any ideas, why this only works in web UI and not over command line?

**Comment by kismetwireless** [comment]
For the command line it's just '-c wlan1' or for more advanced ones, '-c
wlan1:name=foo' and so on

**Comment by JK2210** [comment]
Sorry, my mistake!

**Comment by dandelionnone** [comment]
I get the same error when starting with 'kismet -c wlan0'. The interface is up, and in monitor mode. I verified in Wireshark.

**Comment by dandelionnone** [comment]
Never mind, I realized I had not added myself to the kismet group". Works perfectly now.

**Comment by SMFHS** [comment]
> Never mind, I realized I had not added myself to the kismet group". Works perfectly now.

How do you do that?

**Comment by Raviolibutthole** [comment]
> > Never mind, I realized I had not added myself to the kismet group". Works perfectly now.
> 
> How do you do that?

>>>sudo usermod -aG kismet 'your user'
