### ISSUE TITLE
python 2.7 will soon be deprecated but build requires python2-setuptools

### ISSUE THREAD

**Issue by debragail** [kismetwireless/kismet#159]
configure: error: Missing python2-setuptools, if you would like to build without python entirely, use --disable-python-tools, otherwise install python2-setuptools
Users-MacBook-Air:kismet-2019-07-r1 user$ pip install setuptools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (18.5)

**Comment by ffontaine** [comment]
This issue is fixed since https://github.com/kismetwireless/kismet/commit/681846fe907120b69604cdd120584f236e4b2e44 and https://github.com/kismetwireless/kismet/commit/465beffc5344e936ceceb2782a2388623c3caf20 so it should probably be closed.
