### ISSUE TITLE
Can't compile kismet

### ISSUE THREAD

**Issue by protonesso** [kismetwireless/kismet#163]
Hi, I'm trying to compile kismet version 2019-07-R2. I'm using gcc 9.1.0 and musl libc 1.1.22. I'm using protobuf 3.9.0 and protobuf-c 1.3.1. Configure args (I have replaced config.sub and config.guess):
```
./configure \
	--build=x86_64-linux-musl \
	--prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--disable-python-tools
```
Build log: https://pastebin.com/7VG1FnaK

**Comment by kismetwireless** [comment]
Fixed in git a bit ago, pull that and you should be good to go and it'll be
in the next release.

**Comment by protonesso** [comment]
Okay, thanks!
