### ISSUE TITLE
How do I ge only APs in the Kismet file?

### ISSUE THREAD

**Issue by jmaravi** [kismetwireless/kismet#185]
I want kismet only to show the APs detected in the .kismet file, so far i get all wireless devices detected: clients and APs.

**Comment by kismetwireless** [comment]
That's up to your logic in whatever you process the kismet file device JSON with - you can look either at the basic device type (kismet.device.base.type), or the presence of advertised SSIDs (dot11.device/dot11.device.advertised_ssid_map).

The device json encoded is the same as that presented by the rest endpoints, so check out https://www.kismetwireless.net/docs/devel/webui_rest/exploring/ for some more info on getting all the field descriptions and other device info.
