### ISSUE TITLE
/alerts/last-time/[TIMESTAMP.UTIMESTAMP]/alerts.itjson

### ISSUE THREAD

**Issue by taospartan** [kismetwireless/kismet#186]
Behaviour is not as expected. 
Still returns in ekjson format rather than itjson.

/alerts/all_alerts.itjson and /alerts/all_alerts.json work as expected.

Using the nightly git buld for Debian / Raspbian Buster.

many thanks

Tao

**Comment by kismetwireless** [comment]
This is actually expected, but probably not properly documented, behavior.

That format isn't actually compatible with ekjson OR itjson - when you request a specific time, you get back a dictionary with the current timestamp, and a list of alerts; you can't fetch a dictionary as an ekjson or itjson, only vectors.

I'll update ek and it json to flat-out fail and return an error code when fed an incompatible data type, at the least.

**Comment by taospartan** [comment]
Sorry for the confusion, was utilising the kismet_rest package to interrogate the alerts and made an assumption from the for loop in the example given.

Many thanks

Tao

**Comment by kismetwireless** [comment]
It's a valid assumption, so for now I need to at least throw an error when it's a wrong assumption to make, and add docs for it.  It's an edge case not many people have hit before, i guess.
