### ISSUE TITLE
Question regarding devicefound

### ISSUE THREAD

**Issue by taospartan** [kismetwireless/kismet#187]
When setting the devicefound variable to a valid MAC, kismet detects appearance of device at location and generated an alert. However if devicefound_timeout=60 is given, even after devices wifi has been turned off, timed for 2 minutes then turned back on no more alerts are given. However kismet updates the Last Seen field correctly. 

many thanks

tao

**Comment by kismetwireless** [comment]
Looks like it was only flagging on new devices despite the timeout; pushing new code to git.

**Comment by taospartan** [comment]
Just testing the device found alert, the new code fixes the issue. unfortunately devicelost seems to be none functioning at all.

many thanks

tao
