### ISSUE TITLE
RaspberryPi: Kismet shutdown dhcpd

### ISSUE THREAD

**Issue by Raptime** [kismetwireless/kismet#19]
Hello,
I am running Kismet on a RPi3 using a WiFi dongle and I can't connect to a network on wlan0 while using the dongle for scanning.
It looks like kismet stops dhpcd when I start it, I am using the git version.
Kismet is configured to use the dongle as a source, not the internal wifi and wpa_supplicant is configured to use the internal wifi and not the dongle.
If I start dhcpd after kismet has started everything works fine.
Maybe this is normal behavior but I thought I would mention it.

**Comment by kismetwireless** [comment]
Kismet shouldn't be touching the internal interface; if you're using the older stable code I can't promise it's not doing something else weird, but the modern git code definitely works fine on a pi (and even works w/ the internal interface with nexmon)
