### ISSUE TITLE
Any way to detect connectivity loss with remote capture source?

### ISSUE THREAD

**Issue by ardevd** [kismetwireless/kismet#198]
Unless i'm missing something It doesnt seem to be possible to detect when a remote capture data source looses connection. Is there some sort of periodic ping to ensure the source is still reporting data? Would be useful to have if the functionality does not yet exist.

**Comment by kismetwireless** [comment]
It should go into error state when it's not connected; there is a constant
ping between kismet and capture sources, both local and remote.  There will
also be messages when it disconnects and reconnects.

**Comment by ardevd** [comment]
Thank you!

**Comment by ardevd** [comment]
I can't seem to replicate this behavior. If I poweroff a remote capture source it remains in the data source list and I can't see any alert or message saying the remote source is down. Is this intended behavior?
