### ISSUE TITLE
Kismet and Wireless Security 101 (Mike Kershaw) on YouTube

### ISSUE THREAD

**Issue by MyProjectExpert** [kismetwireless/kismet#216]
Link is to a great video that Mike Kershaw  gave at "SharkFest Wireshark Developer and User Conference".  Title is "Kismet & Wireless Security 101".  

Wiki wasn't working and thought it needed to be posted somewhere here on GitHub for others.

https://www.youtube.com/watch?v=Kk4sImFR4z4&t=1196s  

Thanks Mike Kershaw,  It was very interesting.

**Comment by kismetwireless** [comment]
Thanks, though I don't think raising github issues is the place for this.
