### ISSUE TITLE
Startup Errors

### ISSUE THREAD

**Issue by kertis8763** [kismetwireless/kismet#242]
Please help me fix the errors
![Screenshot at 2020-04-07 13-44-51](https://user-images.githubusercontent.com/23327076/78660773-59042600-78d6-11ea-87d4-ffd7d522500f.png)
![Screenshot at 2020-04-07 13-46-18](https://user-images.githubusercontent.com/23327076/78660783-5e617080-78d6-11ea-8170-1dba6661b4a6.png)

**Comment by DiscoveringWorld** [comment]
Did you run Kismet with an interface ? Did you set your external card in monitor mode?
Example:
sudo ifconfig wlan1 down
sudo iwconfig wlan1 mode monitor
sudo kismet -c wlan1

**Comment by kismetwireless** [comment]
It looks like you installed the proxy test code and are missing some other libraries it expects.  Uninstall that and you'll stop seeing those alerts, but they're not fatal errors and won't affect running kismet.

Putting a card in manual monitor mode has nothing to do with it, and Kismet does that automatically.

**Comment by kismetwireless** [comment]
I pushed the latest kismet-external module to pypi; make sure you have that and the latest kismet git and the example plugin will load fine.
