### ISSUE TITLE
Keeping data after process termination

### ISSUE THREAD

**Issue by DigiAngel** [kismetwireless/kismet#262]
Topic...I'd like to keep the data kismet gathers across start/stop reboots.  So an SSID found will not be considered found again after stopping and starting.

**Comment by DigiAngel** [comment]
Closing due to apparent lack of interest.

**Comment by kismetwireless** [comment]
Currently this would be very difficult; attempts have been made in the past but stability through upgrades (and resources to load saved data) made it untenable.

**Comment by DigiAngel** [comment]
Thank you!
