### ISSUE TITLE
UAV monitoring

### ISSUE THREAD

**Issue by jhplayer** [kismetwireless/kismet#272]
Hi, I'm trying to scan my UAV/Drone, DJI Mavic but doesn't seem to find it. Kismet is picking up other device data ok.

Is there additional Kismet config I need to do, or is this usually down to the Wifi card?

I'm using a AC1200, 8812AU chipset

Kismet is installed on Ubuntu 18.04 Bionic

Thanks

**Comment by kismetwireless** [comment]
It all depends exactly what model.

I believe the mavic is RF only - no wifi, I think it's all occusync (or some flavor thereof). You'd need a SDR, and I don't think there are any public implementations of occusync and friends.

Some DJI drones have wifi between the drone and a phone, or between the RC and the phone.  For the ones that have a RC (Spark and Mavic Air, maybe others) the connection between the RC and the drone is 5mhz quarter-channel atheros custom wifi; it's sniffable, but only with an atheros NIC like the 9k.

**Comment by jhplayer** [comment]
Thanks for feedback. It's a Mavic Air - will give the 9k a try. Thanks
