### ISSUE TITLE
Tracking BLE RSSI

### ISSUE THREAD

**Issue by laurierloi** [kismetwireless/kismet#277]
Using Kismet 20.04, I can detect Bluetooth devices, but the RSSI of the devices doesn't seem to be logged ( n/a is shown in signal column)

I looked at docs, but couldn't find a setting to enable it. Is there a way to enable it?

**Comment by dragorn** [comment]
Currently not supported with the hci bluetooth driver, sorry; will require
additional code that doesn't exist right now.
