### ISSUE TITLE
GPS in PCAPPI log file erratic 

### ISSUE THREAD

**Issue by taospartan** [kismetwireless/kismet#279]
The PCAPPI log file suffers periods of erratic GPS fixes, the GPS antenna doesn't move yet the fixes show movement. This is with kismet connecting to it over serial.
Is there any error correction within kismet for the GPS location when the GPS accuracy lowers?

many thanks in advance

Tao

**Comment by kismetwireless** [comment]
No - kismet is entirely dependent on the gps chip to provide sane data,
either over nmea or over whatever gpsd configures it to do (opaque to
external clients, usually gpsd uses nmea but can also use binary protocols
with some gps units).

Older / cheaper GPS chipsets definitely suffer from significant signal
issues in anything but open skies; I don't know of any embedded AGPS
systems that act like a normal GPS (let alone any affordable ones); they'd
likely still need an active cell connection to benefit from any assistance
seeding/maintaining the GPS.
