### ISSUE TITLE
Persistent storage?

### ISSUE THREAD

**Issue by ffontaine** [kismetwireless/kismet#289]
Persistent storage has been removed more than 2 years ago with 053c8a66145b353d4e5ff99321be133dd2b13289. The message in `kismet_storage.conf` states that this feature is currently being revamped. Is it still true or should this configuration file be removed from kismet?

**Comment by kismetwireless** [comment]
It's not likely to come back any time soon; it introduces more problems
than it solved unfortunately.

**Comment by ffontaine** [comment]
OK, understood, thanks for your prompt answer, then perhaps it would be better to remove `kismet_storage.conf` from the conf directory as well as from https://www.kismetwireless.net/docs/readme/config_files?
