### ISSUE TITLE
Is blockedchannels option interpreted correctly ?

### ISSUE THREAD

**Issue by Matioupi** [kismetwireless/kismet#29]
Hello,

I first launched kismet after standard compile / setup and received messages about non settable channels.
Then I wen't for the blockedchannels option as shown on the command lines.
kismet seems to interpret the command correctly from the first INFO line, but I keep getting the errors about channels that can't be set.

WiFi card is an intel 8260

Regards

`mathieu@ZBook15G3:~/src/kismet$ kismet -c wlp3s0:blockedchannels=\"157,165,165HT40-\"

Kismet server terminated.  Last output:
INFO: Source 'wlp3s0' ignoring channels '157,165,165HT40-'
INFO: Detected new 802.11 Wi-Fi access point BC:C4:93:2F:06:E0 packet 1
INFO: Detected new 802.11 Wi-Fi access point BC:C4:93:2F:06:E1 packet 3
INFO: Detected new 802.11 Wi-Fi access point BC:C4:93:2F:01:D0 packet 17
INFO: Detected new 802.11 Wi-Fi access point BC:C4:93:2F:01:D1 packet 81
INFO: Detected new 802.11 Wi-Fi device 90:6C:AC:8A:9B:20 packet 86
INFO: Detected new 802.11 Wi-Fi device 28:16:AD:73:CB:02 packet 86

mathieu@ZBook15G3:~/src/kismet$ kismet -c wlp3s0:blockedchannels=\"157,165,165HT40-\"
Kismet server terminated.  Last output:
ERROR: wlp3s0 - Could not set channel 149HT40+; ignoring error and 
       continuing (unable to set channel 149/5745 mode 3 via mac80211: 
       error code -1)
ERROR: Interface 'wlp3s0mon' closed: The interface went down
ERROR: Interface 'wlp3s0mon' no longer appears to be up; This can happen when it is unplugged, or another service like DHCP or NetworKManager has taken over and shut it down on us.
ERROR: capture thread ended, source is closed.
ERROR: wlp3s0 - Interface 'wlp3s0mon' closed: The interface went down
ERROR: Data source wlp3s0 (wlp3s0) encountered an error: Interface 
       'wlp3s0mon' closed: The interface went down
ALERT: SOURCEERROR Source wlp3s0 has encountered an error. Kismet will 
       attempt to re-open the source in 5 seconds.  (1 failures)
ERROR: Source wlp3s0 has encountered an error. Kismet will attempt to 
       re-open the source in 5 seconds.  (1 failures)
ERROR: wlp3s0 - Interface 'wlp3s0mon' no longer appears to be up; This can 
       happen when it is unplugged, or another service like DHCP or 
       NetworKManager has taken over and shut it down on us.
ERROR: wlp3s0 - capture thread ended, source is closed.
ERROR: wlp3s0 - Could not set channel 157; ignoring error and continuing 
       (unable to set channel 157/5785 mode 0 via mac80211: error code -31)
`

**Comment by kismetwireless** [comment]
No; with the new data source code that auto-removes channels after they fail it's no longer particularly needed, either, so mention of it has been removed from the readme for now; it may make a reappearance in the future once other code is out of the way, for now, channels which fail repeatedly will be disabled in the list automatically.
