### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ffontaine** [kismetwireless/kismet#290]
Would it be possible to tag a new release? I would like to bump the (very old) kismet version that is used in buildroot without backporting too many commits such as c4ec91b8c244da428bda5098cac242668fe1efc0 which is needed to fix the build with latest libmicrohttpd.

**Comment by kismetwireless** [comment]
It's on the list to do but I'm trying to get several things complete
beforehand to coincide with some other important releases.  Likely in the
coming week to two weeks.

**Comment by ffontaine** [comment]
I'm closing this issue as 2020-09-R1 has been released.
