### ISSUE TITLE
'make install' changes file permission in source tree.

### ISSUE THREAD

**Issue by ehogeweg** [kismetwireless/kismet#297]
File ownership of log_tools/kismetdb_to_pcap and tools/kismet_discovery is changed from non-root to root during 'sudo make instal'l preventing a clean subsequent non-root make.

OS: macOS Catalina-10.15.6

**Comment by dragorn** [comment]
That's an artifact of how make includes the version and build time
information. I don't know of any workaround other than what the makefile
already does, but patches welcome if you find a way.

**Comment by ehogeweg** [comment]
Ok thanks. And I have no clue where to even start looking :-)

So very appreciative of all your hard work.
