### ISSUE TITLE
Safari loses connection.

### ISSUE THREAD

**Issue by ehogeweg** [kismetwireless/kismet#298]
Kismet Browser UI keeps losing connection. Apparently because of a permission issue. Kismet engine runs fine

macOS Catalina.
Tested with Safari and Chrome. Normal mode and private browsing mode.
Running kismet with 'sudo kismet -c ticc2540'
Kismet version 2020-00-GIT as of today (8/26)

Tried running Safari as root but that didn't seem to make a difference.

<img width="501" alt="Screen Shot 2020-08-26 at 20 22 57" src="https://user-images.githubusercontent.com/14045940/91369670-60bb5d00-e7da-11ea-8167-e98264cb4ef7.png">
<img width="916" alt="Screen Shot 2020-08-26 at 20 22 39" src="https://user-images.githubusercontent.com/14045940/91369676-6749d480-e7da-11ea-94ec-5d73b454efce.png">

**Comment by kismetwireless** [comment]
You're probably using the latest libmicrohttpd, which is broken on osx.
Check the compile guide in the readme, you need to manually backlevel the
version brew uses.

As far as I can tell this is a microhttpd error as even their examples
exhibit the same problem.

**Comment by ehogeweg** [comment]
Roger. Thanks for the quick response.
