### ISSUE TITLE
kismet only reports WEP encryption for WPA capable wifi network

### ISSUE THREAD

**Issue by pcabreracamara** [kismetwireless/kismet#30]
Hi all,

I realize that for some wifi networks, kismet only reports "WEP" crypt_set (in the web UI and JSON API). For example;

```
"kismet.device.base.name": "GABRIELA",
"kismet.device.base.username": "",
"kismet.device.base.type": "Wi-Fi AP",
"kismet.device.base.basic_type_set": 1,
"kismet.device.base.crypt": "",
"kismet.device.base.basic_crypt_set": 2,
```

However, using airodump and capturing to PCAP file, the beacon frame only sends Specific Vendor MS WPA information element, but is not sending "RSN Information" element:

Beacon frame in wireshark:
![wireshark-beaconframe](https://user-images.githubusercontent.com/8314063/35152126-607b6c28-fd21-11e7-9ed0-50c99516e91c.png)

However airodump mark encryption as WPA:
![airodump-wpa](https://user-images.githubusercontent.com/8314063/35152131-63f7acf4-fd21-11e7-8bd8-3e8d8301fe8f.png)

Is there any way to force kismet to look/analyze "Specific Vendor MS WPA information element" as airodump does?

Regards,
Pedro

**Comment by kismetwireless** [comment]
Kismet does analyze that field; if you're able to provide a pcap where kismet decodes it wrong I'll take a deeper look.

**Comment by pcabreracamara** [comment]
Hi all,

Find here a pcap with the beacon probes of "RESTAURANTE_CANA" wifi network, shown WEP by kissmet in the Web UI, JSON and SQLite DB:

pcap file:
[all_sources_CANA.pcapng.zip](https://github.com/kismetwireless/kismet/files/1660553/all_sources_CANA.pcapng.zip)

JSON file:
[device_CANA.json.zip](https://github.com/kismetwireless/kismet/files/1660558/device_CANA.json.zip)

Web UI:
![cana](https://user-images.githubusercontent.com/8314063/35342980-c85bb3aa-0129-11e8-9298-9b6b26b54163.png)

Kismet sqlite3 db:
![cana_from_kismet_sql](https://user-images.githubusercontent.com/8314063/35343065-f42660a2-0129-11e8-9a48-957780062630.png)

I check this behaviour with at least 3 more wifi networks (all of them WPA/CCMP/PSK). LEt me know anything else you need from me.
 
Thank you for your response !!

**Comment by kismetwireless** [comment]
Ah, I see now - you're completely right; kismet parses the WPA fields, and the RSN field, but did not parse the WFA-WPA 221 field.  I'm working on a decoder now & will update here; thanks for the pcap!

**Comment by kismetwireless** [comment]
As of kismet commit 4b3fc175783828f5ef7bb1926e750b76e58d7d1f it should be parsing wfa/wpa tags now and incorporating them into the encryption info; it parses the pcap you sent along.  I'll close this for now but if you see more problems feel free to re-open it!

Thanks for the heads up and the pcap
