### ISSUE TITLE
APs/Clients Deriving "Channel" from Neighbors and Shared Hardware 

### ISSUE THREAD

**Issue by Geofferey** [kismetwireless/kismet#317]
After changing how signal is derived (works very nicely btw) a new issue has surfaced. 

When channel hopping is enabled 2.4GHz-5Ghz after a short bit APs and Clients start to show operating under main channels from shared hardware and surrounding neighboring APs. Give it a bit longer and channel will stick to something the AP/Device is surely not broadcasting on. 

I did a test by reverting newest "signal" changes and it doesn't happen. 

Some notes on my environment (maybe relevant):

- I am operating in a dense urban area with many wifi networks

- Many APs in my area operate on 5ghz 80mhz 2.4 20mhz wide with SSIDs merged instead of having separate SSID for each band.

 - Here is my channel hopping configuration...

    source=wlan0mon:name="qcacld-3",channels="1,6,11,36VHT80,40VHT80,44VHT80,48VHT80,52VHT80,56VHT80,60VHT80,64VHT80,132VHT80,136VHT80,140VHT80,144VHT80,149VHT80,153VHT80,157VHT80,161VHT80"

- I have also uploaded pcap from the session 
https://file.io/X6JdCeLc2X8f which was recorded up until first screenshots. 

I have made some screenshots to highlight this issue...

![IMG_20201026_205453](https://user-images.githubusercontent.com/7959069/97255503-06d11680-17ce-11eb-9d98-bb80eac38cbf.jpg)

![IMG_20201026_205559](https://user-images.githubusercontent.com/7959069/97255499-05075300-17ce-11eb-9fbc-ebba18cbbf97.jpg)

I do see the "main frequency" is correct so wouldn't it be possible to match the "channel" to the frequency seen most? Although I don't see why we should be picking up any 5ghz packets from a device not even capable of broadcasting on that band, especially if it's parent AP isn't either. 

Here is interesting case. These two devices had the same signal reporting issues after initial fixes as cameras I described (fixed now). Their parent AP does operate on both hands with SSID merged the 5GHz band on control 100 80MHz and 2.4 on 1 but the devices themselves are only 2.4ghz capable like the cameras. 

![Screenshot_Chrome_20201026-220112~2](https://user-images.githubusercontent.com/7959069/97259202-74ce0b80-17d7-11eb-9672-bfe970746dde.png)

![IMG_20201026_221038](https://user-images.githubusercontent.com/7959069/97259486-19e8e400-17d8-11eb-9a91-4e978b4fca0c.jpg)

The packet frequency distribution however doesn't even show 5ghz for these two devices. Starting to seem like devices that reported same as AP signal after initial fixes are exhibiting similar in regards to the displayed channel.

**Comment by Geofferey** [comment]
Here's trying to give you something to go off of. I commented out these two blocks of code and the problem has disappeared with cams. I don't know implication of doing this and it probably breaks something else, but looks like part of problem is here.

        //Suspect #2

        /*if (dot11info->dest_mac != dot11info->source_mac &&
                dot11info->dest_mac != dot11info->bssid_mac &&
                dot11info->dest_mac != globalreg->empty_mac &&
                !(dot11info->dest_mac.bitwise_and(globalreg->multicast_mac)) ) {

            dest_dev =
                d11phy->devicetracker->update_common_device(commoninfo,
                        dot11info->dest_mac, d11phy, in_pack,
                        (update_flags | UCD_UPDATE_PACKETS | UCD_UPDATE_SEENBY),
                        "Wi-Fi Device");
        }*/

        //Suspect #3

        /*if (dot11info->other_mac != dot11info->source_mac &&
                dot11info->other_mac != dot11info->dest_mac &&
                dot11info->other_mac != dot11info->bssid_mac &&
                dot11info->other_mac != globalreg->empty_mac &&
                !(dot11info->other_mac.bitwise_and(globalreg->multicast_mac)) ) {

            other_dev =                                                                                          d11phy->devicetracker->update_common_device(commoninfo,                                                  dot11info->other_mac, d11phy, in_pack,
                        (update_flags | UCD_UPDATE_PACKETS | UCD_UPDATE_SEENBY),                                                             "Wi-Fi Device");
        }*/

Been running on hopping for about 20 min and still hasn't shown error with channel

![Screenshot_Chrome_20201027-011130~2](https://user-images.githubusercontent.com/7959069/97274132-74db0500-17f1-11eb-8780-ce741f24df40.png)

![Screenshot_Chrome_20201027-011316~2](https://user-images.githubusercontent.com/7959069/97274342-c2f00880-17f1-11eb-8cff-9fabd66edbbe.png)

**Comment by dragorn** [comment]
That removes associating target devices, so yea - that's going to make
devices disappear and not be identified, because you removed the ability to
identify them.

Neither of those blocks sets the frequency.

It's entirely normal to see client devices hopping around on different
frequencies; you're going to need to go through your pcaps and see what
they're doing on the wifi layer and on the radiotap signal header to see
what frequencies each individual packet is on.

**Comment by Geofferey** [comment]
Is it normal to see client devices that have absolutely zero hardware support for 5GHz to show that they have been on a 5GHz channel? I'd get what you're saying if they did support 5Ghz but these devices like cams and lights do not have to ability to communicate on that band. Id also understand if the cameras AP was operating on a 5Ghz as well but it doesn't and the cams still  end up as operating under 5Ghz channels. 

Let's say hypothetically that the camera did have some kind of hidden 5ghz capabilities. Even then the packet distribution shows over 90% on 2.462 (CH11) so why does UI end up showing channel 48 and getting stuck on that because it supposedly saw a small bit of traffic on that freq? In my mind the channel column / last seen channel should either match the last seen channel or be derived based on the packet distribution. Basically it would make sense (to me) if it showed same info as main frequency but in channel format. 

Seriously tho, after removing that block of code it stopped with clients like cams but not APs. I add back and cams end up showing control freq 48 and not 11 which they mostly operate on. I know it doesn't make any sense because I can see it doesn't have the UCD_UPDATE_FREQUENCIES in it so how it's effecting this I have zero idea. 

Anyways I didn't noticed any issues with this until the signal stuff was fixed. Sadly this is a game code likes to play lmfao .

**Comment by kismetwireless** [comment]
it's normal if your card is lying and reporting them on 5ghz because it's
got sync problems with the channel set, that's for sure - which is why you
need to look at the packets and see what's being reported by the card in
the radiotap signal headers.

It's also normal if you have a 5ghz AP bridging broadcast packets from the
device onto 5ghz.  Which you also need to look at the pcap and see if it's
only on broadcast packets from the AP, but that code explicitly does NOT
set signal levels on the inferred destination device.

>

**Comment by Geofferey** [comment]
I did take a pcap like you said, I dont know exactly what I should be looking for to help you but I did upload it 

https://file.io/X6JdCeLc2X8f

If this is an issue with my driver/card tho why would it just be showing up now? This did not happen before. Also it could be combated by doing what I said and having the last seen channel be based off the same "main freq" that's showing in shots. It wouldn't truly be last seen anymore but at least it would show correct the most seen freq (main freq) in channel column when sorting on first page. 

The data is contradicting itself just based on the screenshots I uploaded and that's what I am not liking. The devices in shots are clearly operating 90% in 2.4ghz band based on data even if there is a bit of false information caused by a wonky card/driver/hopping. So, why not just have last channel be derived from main frequency info then?

**Comment by Geofferey** [comment]
I'm pretty sure I've found the block of code that is responsible for the issues I've been experiencing with the channel column. 

     if (dot11info->channel != "0" && dot11info->channel != "") {
                bssid_dev->set_channel(dot11info->channel);
            } else if (pack_l1info != NULL && (pack_l1info->freq_khz != bssid_dev->get_frequency() ||
                    bssid_dev->get_channel() == "")) {
                try {
                    bssid_dev->set_channel(khz_to_channel(pack_l1info->freq_khz));
                } catch (const std::runtime_error& e) {
                    ;
                }
            }

After commenting out all blocks containing `if (dot11info->channel != "0" && dot11info->channel != "")` The column is probably somewhere in the realm of 95-90% accuracy. This certainly breaks the channel field in device page > device info > Channel (?) > "The phy-specific channel of the device, if known...." but there is huge improvement of accuracy in nearly any other field that shows a channel, especially the column.

**Comment by kismetwireless** [comment]
As you note, that removes channel setting, so, yes - it will stop showing
channels, but I don't consider that a viable change to the code since it
stops ALL channel handling, and removes all classification of channels on
non-2.4ghz devices.

You don't seem to want to believe it or look at the pcaps, but here's proof
of the exact thing I'm talking about re: wi-fi drivers reporting the wrong
frequency for received packets, and theres nothing Kismet can do about it
(attached); that's with the mediatek in-kernel drivers which are otherwise
excellent, other drivers are likely even less reliable.

**Comment by Geofferey** [comment]
You obviously do not fully read these.... maybe you don't have enough time, idk. 

Instead of replying by email actually go and look what I have written here because it is constantly edited. I don't just go around making this stuff up to troll you, yet you seem to think I'm full of it. I am more than willing to look at PCAPs but it kinda helps if I know what to look for, which I don't. Also, I could fully believe it was a driver error if devices/APs weren't showing the EXACT same control channels as neighboring APs and shared hardware in the column/info page... There is a direct correlation between what I am seeing and the signal fixes 0a8e67f9. There is also a direct correlation in the crossing of displayed channels, not just some randomness or adjacent channel in the overlap. Anyways, for the hundread millionth time it did not happen before, but I guess I'm just making that up as well.

**Comment by Geofferey** [comment]
Working on a possible solution to this. If the code works I'll share with you guys. I think it will be beneficial for everyone and shouldn't break things for others.
