### ISSUE TITLE
Kismet crashing while scanning all channels

### ISSUE THREAD

**Issue by djjerdog** [kismetwireless/kismet#33]
I just updated to the latest code and I'm getting this error after a minute our so when scanning all channels.

Kismet server terminated.  Last output:
4    Object "/usr/lib/aarch64-linux-gnu/libstdc++.so.6.0.22, at 0xffff8143d347, in std::__throw_ios_failure(char const*)
#3    Object "/usr/lib/aarch64-linux-gnu/libstdc++.so.6.0.22, at 0xffff8141501b, in __cxa_throw
#2    Object "/usr/lib/aarch64-linux-gnu/libstdc++.so.6.0.22, at 0xffff81414d97, in std::terminate()
#1    Object "/usr/lib/aarch64-linux-gnu/libstdc++.so.6.0.22, at 0xffff81414d4b, in 
#0    Source "/home/wlanpi/kismet/kismet_server.cc", line 417, in TerminationHandler
        415: #ifndef DISABLE_BACKWARD
        416:     using namespace backward;
      > 417:     StackTrace st; st.load_here(32);
        418:     Printer p; p.print(st);
        419: #endif
Kismet exited.

**Comment by kismetwireless** [comment]
Ok; if you could take a look at the debugging section in the readme and post the stack trace I'll take a look, thanks!

**Comment by kismetwireless** [comment]
Coordinated via email; should be fixed in the latest commits (missing try/catch on rmm IE fields)
