### ISSUE TITLE
API `Alerts - device presence / absence - viewingPermalink` NOT WORK

### ISSUE THREAD

**Issue by yaphone** [kismetwireless/kismet#330]
hi,
    I have been used Kismet for moths,  recently I updated my Kismet version to `Kismet 2020-12-R3`, as its doc describe, it has a new api  [Alerts - device presence / absence - viewingPermalink ](https://www.kismetwireless.net/docs/devel/webui_rest/devices/#alerts---device-presence--absence---viewing), but I found it NOT work as expect, when send a GET request url as `String url = kismetServerUrl + "/devices/alerts/mac/found/list.json"`,  it returns

`<html><head><title>404 not found</title></head><body><h1>404 Not Found</h1><br><p>Could not find <code>&#x2F;devices&#x2F;alerts&#x2F;mac&#x2F;found&#x2F;list.json</code></p></body></html>`

can anyone help? Thank you very much!

**Comment by kismetwireless** [comment]
Docs updated; should be 'macs.json'

**Comment by yaphone** [comment]
THX a lot, it works well !!
