### ISSUE TITLE
Relative (negative) timestamps not working with '/devices/last-time/[timestamp]/devices.json'

### ISSUE THREAD

**Issue by mainakae** [kismetwireless/kismet#333]
Tested on a armhf, 2020-12-R3a (on a Raspberry Pi 4). The non negative version works just fine, but when setting relative timestamps, it returns always all the devices (from the beginning of the scanning).

Thanks for the great work, congratulations and happy christmas!

**Comment by kismetwireless** [comment]
Which endpoint are you trying to use?  I can't recreate it so far, here:

curl http://kismet:kismet@localhost:2501/device/views/all/last-time/-10/devices.itjson

for instance returns the expected number of devices.

Is there any chance you have an odd keyboard/language setting where your '-' in the URI isn't a standard 0x2D ascii '-'?

**Comment by kismetwireless** [comment]
Oh; i think i spot it in the original /devices/last-time/ endpoint.
