### ISSUE TITLE
Following error when trying to compile on RPI 4

### ISSUE THREAD

**Issue by builder2020** [kismetwireless/kismet#336]
$ make
protoc --cpp_out=./protobuf_cpp/ -I protobuf_definitions/ protobuf_definitions/kismet.proto
protoc --cpp_out=./protobuf_cpp/ -I protobuf_definitions/ protobuf_definitions/http.proto
protoc --cpp_out=./protobuf_cpp/ -I protobuf_definitions/ protobuf_definitions/datasource.proto
protoc --cpp_out=./protobuf_cpp/ -I protobuf_definitions/ protobuf_definitions/linuxbluetooth.proto
protoc --cpp_out=./protobuf_cpp/ -I protobuf_definitions/ protobuf_definitions/eventbus.proto
protoc --cpp_out=./protobuf_cpp/ -I protobuf_definitions/ protobuf_definitions/kismet.proto
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT protobuf_cpp/kismet.pb.cc.o protobuf_cpp/kismet.pb.cc -MF protobuf_cpp/kismet.pb.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c protobuf_cpp/kismet.pb.cc -o protobuf_cpp/kismet.pb.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT protobuf_cpp/http.pb.cc.o protobuf_cpp/http.pb.cc -MF protobuf_cpp/http.pb.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c protobuf_cpp/http.pb.cc -o protobuf_cpp/http.pb.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT protobuf_cpp/datasource.pb.cc.o protobuf_cpp/datasource.pb.cc -MF protobuf_cpp/datasource.pb.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c protobuf_cpp/datasource.pb.cc -o protobuf_cpp/datasource.pb.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT protobuf_cpp/linuxbluetooth.pb.cc.o protobuf_cpp/linuxbluetooth.pb.cc -MF protobuf_cpp/linuxbluetooth.pb.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c protobuf_cpp/linuxbluetooth.pb.cc -o protobuf_cpp/linuxbluetooth.pb.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT protobuf_cpp/eventbus.pb.cc.o protobuf_cpp/eventbus.pb.cc -MF protobuf_cpp/eventbus.pb.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c protobuf_cpp/eventbus.pb.cc -o protobuf_cpp/eventbus.pb.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT util.cc.o util.cc -MF util.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c util.cc -o util.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT macaddr.cc.o macaddr.cc -MF macaddr.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c macaddr.cc -o macaddr.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT uuid.cc.o uuid.cc -MF uuid.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c uuid.cc -o uuid.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT xxhash.cc.o xxhash.cc -MF xxhash.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c xxhash.cc -o xxhash.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT boost_like_hash.cc.o boost_like_hash.cc -MF boost_like_hash.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c boost_like_hash.cc -o boost_like_hash.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT sqlite3_cpp11.cc.o sqlite3_cpp11.cc -MF sqlite3_cpp11.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c sqlite3_cpp11.cc -o sqlite3_cpp11.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT globalregistry.cc.o globalregistry.cc -MF globalregistry.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c globalregistry.cc -o globalregistry.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT eventbus.cc.o eventbus.cc -MF eventbus.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c eventbus.cc -o eventbus.cc.o
g++ -std=gnu++17 -MM -MP -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -MT packet.cc.o packet.cc -MF packet.cc.d
g++ -std=gnu++17 -Wall -Wno-unknown-warning-option -Wno-deprecated-declarations -Wno-format-truncation -Wno-unused-local-typedefs -Wno-unused-function -Wno-infinite-recursion -g -I. -fPIE -g -O2 -O3 -pthread -DKS_STR_ENCODING_NONE   -c packet.cc -o packet.cc.o
In file included from packet.cc:36:
packetchain.h:167:10: error: ‘shared_mutex’ in namespace ‘std’ does not name a type
     std::shared_mutex packetchain_mutex;
          ^~~~~~~~~~~~
packetchain.h:167:5: note: ‘std::shared_mutex’ is defined in header ‘<shared_mutex>’; did you forget to ‘#include <shared_mutex>’?
packetchain.h:48:1:
+#include <shared_mutex>

packetchain.h:167:5:
     std::shared_mutex packetchain_mutex;
     ^~~
cc1plus: warning: unrecognized command line option ‘-Wno-infinite-recursion’
cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
make: *** [Makefile:752: packet.cc.o] Error 1

Config:

$ ./configure
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether make sets $(MAKE)... yes
checking how to run the C preprocessor... gcc -E
checking for platform-specific compiler flags... none needed
checking gcc version... 8
checking whether g++ supports C++17 features with -std=gnu++17... yes
checking how to run the C++ preprocessor... g++ -std=gnu++17 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking python3 module: setuptools... yes
checking for dwarf_begin in -ldw... yes
checking for bfd_alloc in -lbfd... no
checking elfutils/libdw.h usability... yes
checking elfutils/libdw.h presence... yes
checking for elfutils/libdw.h... yes
checking elfutils/libdwfl.h usability... yes
checking elfutils/libdwfl.h presence... yes
checking for elfutils/libdwfl.h... yes
checking dwarf.h usability... yes
checking dwarf.h presence... yes
checking for dwarf.h... yes
checking unwind.h usability... yes
checking unwind.h presence... yes
checking for unwind.h... yes
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking for stdint.h... (cached) yes
checking for strerror_r() return... char *
checking for accept() addrlen type... socklen_t
checking for pipe2... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking for dlopen in -ldl... yes
checking for deflate in -lz... yes
checking for pthread_mutex_timedlock... no
checking for libm math function in std libs... yes
checking for main in -lstdc++... yes
checking for group 'root'... yes
checking for setproctitle... no
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking for setproctitle in -lutil... no
checking sys/pstat.h usability... no
checking sys/pstat.h presence... no
checking for sys/pstat.h... no
checking whether __progname and __progname_full are available... yes
checking which argv replacement method to use... writeable
checking for linux/wireless.h... yes
checking that linux/wireless.h is what we expect... yes
checking can we use iw_freq.flags... yes
checking for pcre_compile in -lpcre... yes
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes
checking for sqlite3_libversion in -lsqlite3... yes
checking sqlite3.h usability... yes
checking sqlite3.h presence... yes
checking for sqlite3.h... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libwebsockets... yes
checking for lws_client_connect_via_info in -lwebsockets... yes
checking for libpcap... no
configure: WARNING: No libpcap found in pkg-config
checking for pcap_open_live in -lpcap... yes
checking pcap.h usability... yes
checking pcap.h presence... yes
checking for pcap.h... yes
checking for protobuf... yes
checking for protoc... yes
checking for libprotobufc... yes
checking for protoc-c... yes
Using local radiotap headers
checking for libnm... yes
checking For nm_device_set_managed in libnm... checking for libnl30... yes
checking for libnlgenl30... yes
checking for libnl20... no
checking for libnl1... no
checking For mac80211 support in netlink library... yes
checking for libusb... yes
checking btbb.h usability... yes
checking btbb.h presence... yes
checking for btbb.h... yes
checking for btbb_init in -lbtbb... yes
checking ubertooth/ubertooth.h usability... no
checking ubertooth/ubertooth.h presence... no
checking for ubertooth/ubertooth.h... no
checking ubertooth.h usability... no
checking ubertooth.h presence... no
checking for ubertooth.h... no
checking for ubertooth_init in -lubertooth... no
configure: WARNING: missing libubertooth, ubertooth-one support will not be built
configure: WARNING: missing one or more required libraries for ubertooth-one
checking sensors/sensors.h usability... yes
checking sensors/sensors.h presence... yes
checking for sensors/sensors.h... yes
checking for sensors_init in -lsensors... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating Makefile.inc
config.status: WARNING:  'Makefile.inc.in' seems to ignore the --datarootdir setting
config.status: creating packaging/kismet.pc
config.status: creating packaging/systemd/kismet.service
config.status: creating packaging/systemd/debug/kismet-debug.service
config.status: creating capture_linux_bluetooth/Makefile
config.status: creating capture_linux_wifi/Makefile
config.status: creating capture_osx_corewlan_wifi/Makefile
config.status: creating capture_sdr_rtl433/Makefile
config.status: creating capture_sdr_rtlamr/Makefile
config.status: creating capture_sdr_rtladsb/Makefile
config.status: creating capture_freaklabs_zigbee/Makefile
config.status: creating capture_nrf_mousejack/Makefile
config.status: creating capture_ti_cc_2540/Makefile
config.status: creating capture_ti_cc_2531/Makefile
config.status: creating capture_ubertooth_one/Makefile
config.status: creating capture_nrf_51822/Makefile
config.status: creating capture_nxp_kw41z/Makefile
config.status: creating config.h

Configuration complete:
         Compiling for: linux-gnueabihf (armv7l)
           C++ Library: stdc++
      Protobuf Library: protobuf
   Installing as group: root
       Installing into: /usr/local
          Setuid group: kismet
        Prelude  SIEM : no
            PCRE regex: yes
 Websocket datasources: yes
LibCapability (enhanced
   privilege dropping): no
  Linux Wi-Fi capture : yes
         Linux Netlink: yes (mac80211 VAP creation) - libnl-3.0 libnl-genl-3.0
  Linux NetworkManager: yes (libnm NetworkManager control)
   Linux HCI Bluetooth: yes
   OSX/Darwin capture : n/a (only OSX/Darwin)
         nRF MouseJack: yes
       TI CC 2540 BTLE: yes
     TI CC 2531 Zigbee: yes
         Ubertooth One: no (libubertooth, libbtbb, or libusb-1.0 not available)
         NRF51822 BTLE: yes
  NXP KW41Z BLE/Zigbee: yes
        Python Modules: yes
    Python interpreter: python3
       RTL-SDR RTL_433: yes
        RTL-SDR RTLAMR: yes
       RTL-SDR RTLADSB: yes
      Freaklabs Zigbee: yes
 lm-sensors monitoring: yes
        Built-in Debug: yes - Full debug info available on crash, using unwind

**Comment by pahanco** [comment]
I had such error when I tried to compile last master branch, so upgrading gcc to version 10 helped me.
