### ISSUE TITLE
kismet.conf error "wlan0" can not be identified

### ISSUE THREAD

**Issue by EastwindZL** [kismetwireless/kismet#34]
Data source 'wlan0' failed to launch: Unable to find driver for 
       'wlan0'.  Make sure that any plugins required are loaded.

![20180214_110349](https://user-images.githubusercontent.com/29472751/36186028-5afe2c80-1177-11e8-8e51-4e777ca29175.png)
![20180214_110409](https://user-images.githubusercontent.com/29472751/36186029-5b47babc-1177-11e8-8de6-e100860ee571.png)

**Comment by kismetwireless** [comment]
See the error 3 or 4 lines above and make sure your user is in the correct group.
