### ISSUE TITLE
validmacs accepts only a single MAC address

### ISSUE THREAD

**Issue by kovaga** [kismetwireless/kismet#343]
In a situation where multiple APs advertise the same SSID, including those macs in the validmacs field separating them with coma results in all of the macs being ignored and detected as APSPOOF.
Entering a single MAC in the validmacs field works OK.

**Comment by dragorn** [comment]
For multiple macs they must be enclosed in quotes; ie

apspoof=foo:ssid="foo",validmacs="mac1,mac2,mac3"

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kovaga** [comment]
Yes, I enclose them in quotes. Here is the line from the kismet_alerts.conf
apspoof=Home:ssid="HAP",validmacs="fc:ec:da:XX:XX:AA,fc:ec:da:XX:XX:BB,f0:9f:c2:XX:XX:CC,f0:9f:c2:XX:XX:DD"
