### ISSUE TITLE
SOURCEERROR Source wlp1s0u1u1mon has encountered an error. Kismet

### ISSUE THREAD

**Issue by michaelmohamed** [kismetwireless/kismet#344]
```
[Logs]    [3/3/2021, 1:52:14 PM] [] ERROR: All configured channels are in error state!
[Logs]    [3/3/2021, 1:52:14 PM] [] ERROR: Data source 'wlp1s0u1u1mon / wlp1s0u1u1mon' ('wlp1s0u1u1mon') encountered an error: Fatal error from remote source
[Logs]    [3/3/2021, 1:52:14 PM] [] ALERT: SOURCEERROR Source wlp1s0u1u1mon has encountered an error. Kismet will attempt to re-open the source in 5 seconds.  (1 failures)
[Logs]    [3/3/2021, 1:52:14 PM] [] ERROR: Source wlp1s0u1u1mon has encountered an error. Kismet will attempt to re-open the source in 5 seconds.  (1 failures)
[Logs]    [3/3/2021, 1:52:19 PM] [] INFO: Attempting to re-open source wlp1s0u1u1mon
[Logs]    [3/3/2021, 1:52:19 PM] [] INFO: wlp1s0u1u1mon could not connect to NetworkManager, cannot automatically prevent interface 'wlp1s0u1u1mon' from being modified if NetworkManager is running: Could not connect: No such file or directory
[Logs]    [3/3/2021, 1:52:19 PM] [] INFO: wlp1s0u1u1mon interface 'wlp1s0u1u1mon' is already in monitor mode
[Logs]    [3/3/2021, 1:52:19 PM] [] INFO: wlp1s0u1u1mon finished configuring wlp1s0u1u1mon, ready to capture
[Logs]    [3/3/2021, 1:52:19 PM] [] ALERT: SOURCEOPEN Source wlp1s0u1u1mon successfully re-opened
c[Logs]    [3/3/2021, 1:52:23 PM] [] ERROR: All configured channels are in error state!
[Logs]    [3/3/2021, 1:52:23 PM] [] ERROR: Data source 'wlp1s0u1u1mon / wlp1s0u1u1mon' ('wlp1s0u1u1mon') encountered an error: Fatal error from remote source
[Logs]    [3/3/2021, 1:52:23 PM] [] ALERT: SOURCEERROR Source wlp1s0u1u1mon has encountered an error. Kismet will attempt to re-open the source in 5 seconds.  (1 failures)
[Logs]    [3/3/2021, 1:52:23 PM] [] ERROR: Source wlp1s0u1u1mon has encountered an error. Kismet will attempt to re-open the source in 5 seconds.  (1 failures)
```

I am using an external wifi adapter. I get this issue after a few minutes of running 2020-12-R3. Everything seems to work, mac addresses are output, and then there is the failure/continuous tries to reconnect. It sometimes works, then fails again.

If I use 2016-07-R1, I have no problem.

**Comment by dragorn** [comment]
What OS? What kernel? What is the card type? Did you upgrade the remote sources as well?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by michaelmohamed** [comment]
Thanks for the quick response.

Hi, I am on a Raspberry Pi 4, Kernel 5.4.83-v8, using Kali Linux inside of a docker container.

I am not using any remote sources. 

My source is set as `source= wlp1s0u1u1mon`

**Comment by michaelmohamed** [comment]
I may have resolved the issue. I will report back and close if all is OK.

Before I started Kismet, I would run 

```
airmon-ng stop ${WIFI_SOURCE}mon
airmon-ng start $WIFI_SOURCE
kismet --no-ncurses -c wlp1s0u1u1mon
```


When I changed to:

```
kismet --no-ncurses -c wlp1s0u1u1
```

It seems to work. Not sure what is happening here but allowing kismet to set the monitoring mode, things seem OK.

**Comment by kismetwireless** [comment]
Nexmon needs specific configuration or it won't make proper monitor interfaces, correct. I would definitely let kismet do it, unless you're sure you're doing the specific nexmon commands.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by michaelmohamed** [comment]
It is very odd. This error is happening once every hour or so.

**Comment by kismetwireless** [comment]
Sounds like "normal" nexmon behavior to me, it's not a very stable patch in monitor mode and is highly dependent on a lot of other factors.

That error means the driver stopped accepting channel set commands; either the driver crashed out, the card stopped responding and the driver crashed out, or something else on your system took over the interface and took it out of monitor mode so it no longer accepts channel set commands (ie, put another vif in managed mode or something like that).

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by michaelmohamed** [comment]
Thanks for the insight! This was very helpful.

Much appreciated @kismetwireless @dragorn

**Comment by michaelmohamed** [comment]
It seems that the problem was happening about every 7 minutes. I was able to figure out that the NetworkManager may have been trying to take control. 

```
# Showed that wlp1s0u1u1 as "disconnected"
nmcli dev status

# Changed the device to be unmanaged (solution)
nmcli device set wlp1s0u1u1 managed no
```

**Comment by michaelmohamed** [comment]
This is likely related to the kismet output:

```
[Logs]    [3/4/2021, 10:34:57 AM] [] INFO: wlp1s0u1u1 could not connect to NetworkManager, cannot automatically prevent interface 'wlp1s0u1u1' from being modified if NetworkManager is running: Could not connect: No such file or directory
```

**Comment by michaelmohamed** [comment]
The ultimate solution was to add `ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket` to my docker file.
