### ISSUE TITLE
Is it possible to use a single SDR?

### ISSUE THREAD

**Issue by michaelmohamed** [kismetwireless/kismet#346]
Quick question. Is it possible to use a single SDR to perform various collections simultaneously? e.g. wifi, ble, adsb, and others.

If so, are there disadvantages to doing so?

**Comment by dragorn** [comment]
No. Those are all at significantly disparate frequencies so it wouldn't be possible to capture them simultaneously.

You're better off getting multiple cheap sdr devices for the simpler protocols.

-------- Original Message --------
