### ISSUE TITLE
Step 7 (errors)

### ISSUE THREAD

**Issue by swiftdev2017** [kismetwireless/kismet#35]
Hello guys, I had some problems during the installation:

7. Compile Kismet $ make

First, I had to do a cd kismet in order to lunch this command.
After As you said I had some warnings, but at the end of this command I had some errors:

**### In file included from tracked_location.cc:21:
In file included from ./tracked_location.h:22:
./config.h:415:17: warning: using directive refers to implicitly-defined namespace 'std'
using namespace std;
                ^
tracked_location.cc:389:19: error: no member named 'isnan' in namespace 'std'
        if (!std::isnan(alt / num_alt))
             ~~~~~^
tracked_location.cc:439:23: error: no member named 'isnan' in namespace 'std'
            if (!std::isnan(alt / num_alt))
                 ~~~~~^
2 warnings and 2 errors generated.**

Could you help me to resolve this issue?
Thanks in advance.

Jay

**Comment by kismetwireless** [comment]
Should be addressed in the latest commits.
