### ISSUE TITLE
core dumped when gpsd is set in config but service is down

### ISSUE THREAD

**Issue by mm-e1** [kismetwireless/kismet#355]
I get the following error when gpsd is set in the config as:`gps=gpsd:host=localhost,port=2947`, but the gpsd service is not running. 

INFO: (GPS) Connecting to GPSD on localhost:2947
Segmentation fault      (core dumped) kismet --no-ncurses

version: Kismet 2020-12-R3

I expect this to not throw a fatal error, but instead try to reconnect to gpsd throughout the application lifecycle.

**Comment by dragorn** [comment]
Please try with the latest git code or tomorrow's nightly builds. If it continues to fail, please use the debugging directions in the documentation section of the website and I'll take a look.

-------- Original Message --------
