### ISSUE TITLE
Current endpoint providing "kismet.device.packets_rrd"

### ISSUE THREAD

**Issue by notaco** [kismetwireless/kismet#381]
In 2020.12.R3 and prior "kismet.device.packets_rrd" is provided in /system/status.json. I have compiled 2021.06.R1 and 2021.05.R1 where it appears in tracked_fields.html but not in status.json. I saw a number of commits regarding changes to API so I was wondering if it has been relocated. 

Thanks!

**Comment by kismetwireless** [comment]
Looks like that one slipped through the cracks on the docs; added.

https://www.kismetwireless.net/docs/devel/webui_rest/system_status/#packet-counts

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by notaco** [comment]
Thanks for clarifying. Noticed packetchain in commit titles and relevant RRDs coming through the websockets in the gui. Glad to see they are still available in the json endpoint.
