### ISSUE TITLE
Import multiple pcaps?

### ISSUE THREAD

**Issue by Twink-Polar** [kismetwireless/kismet#384]
Not so much an issue but a query. I know you can start kismet with "-c" to read a pcap and load it. 

Is that option limited to 1 pcap or can you do multiple pcaps at once?

**Comment by dragorn** [comment]
You can just specify multiple -c options and load them all at once as different sources, or you can merge them together with something like mergecap first. Either should work fine!

-------- Original Message --------

**Comment by Twink-Polar** [comment]
Brilliant. So as an example I could do:

Kismet -c 1.pcap -c 2.pcap -c 3.pcap
