### ISSUE TITLE
Location "history cloud"

### ISSUE THREAD

**Issue by curious-ninja** [kismetwireless/kismet#391]
Hello,

I noticed that the location history cloud was removed back in November 2020, at this commit:
https://github.com/kismetwireless/kismet/commit/b6255ed67c397718aa080c5b3364215966ec380e

The commit description states: 
"remove location history pseudo-rrd to be replaced with a SQL lookup in the future"

The changelog for release 2020-12-R1 shows:
Location data no longer includes the ‘history cloud’, an attempt to provide a RRD-like history log; it used way too much RAM and was not used anywhere.

Is there a planned replacement for this feature? Or is the removal permanent?
I was using the history cloud in an external leaflet map to plot device history and am curious about this removal.
The alternative for me is to process the .kismet dblog file for the data myself at a set interval, which can be time consuming for a large log file.

Thanks

**Comment by kismetwireless** [comment]
This should be restored in the latest git; it does add quite a bit of ram consumption so it's disabled by default in the configs, but you can turn it on w/ the previous option; keep_location_cloud_history=true ...  the new ram saving tricks are in place w/ the restored code, so it shouldn't use ram when it's disabled; i'll close this for now but if the restored code isn't acting right feel free to re-open it; it looks like it's performing as it used to though.

**Comment by curious-ninja** [comment]
Wow that was fast! Really appreciate this, thank you!
