### ISSUE TITLE
kismet -c <datasource.kismet> not showing all devices

### ISSUE THREAD

**Issue by mmbaguette** [kismetwireless/kismet#411]
After going war-driving, I was using my phone on the Kismet web interface to check how many devices I found at the end: **over a thousand**. However, when I saved then loaded the `.kismet` database using `kismet -c kismetfile.kismet`, the web interface keeps showing me a different number everytime I load the file.

*Starting Kismet*
![image](https://user-images.githubusercontent.com/76597978/156952665-59def267-6b45-4c31-8f7a-6bc0b560518e.png)

*Reload*
![image](https://user-images.githubusercontent.com/76597978/156952727-cd395e6a-34a6-450e-9a31-b6f8e3e80da8.png)

And this just keeps happening. I know for a fact that the missing devices I'm looking for are in the same file, because I did a grep keyword search on the `.kismet` file, and I even found it once after reloading several times. Is this a bug or should I be doing something differently?

**Comment by solsticedhiver** [comment]
when loading a kismetdb file, kismet does read as fast as it can the file and try to process all devices. but that may overwhelm your cpu/RAM and your pc/laptop/whatever you are using.

You can limit the speed rate at which kismet process the devices by using the pps option like explained in the doucmentation at https://kismetwireless.net/docs/readme/datasources_kismetdb/

Use something like:

    kismet -n -c kismetfile.kismet,pps=5000

and adjust the pps value until you don't see any dropped packages/devices anymore

That should fix you problem
If that answers your question, please close the issue. Thanks
