### ISSUE TITLE
Kismet fails to build on gentoo with libfmt-9.0.0

### ISSUE THREAD

**Issue by RockyBukake** [kismetwireless/kismet#425]
There's no issue building with libfmt-8.1.1, [build.log](https://github.com/kismetwireless/kismet/files/9282437/build.log)

**Comment by dragorn** [comment]
Kismet includes it's own header-based copy of libfmt because most distros don't include it, it shouldn't be linking against a system libfmt (or any libfmt, as it uses the header-only version).

**Comment by dragorn** [comment]
No idea - i haven't explored libfmt9 at all, sorry.

**Comment by ZeroChaos-** [comment]
I have been building against the system libs as it's very frowned upon to use bundled libs.  It's my fault, but please update your libfmt when you can so I can continue to be a problem and use the system copy :-)
