### ISSUE TITLE
Official site still uses deprecated "apt-key"

### ISSUE THREAD

**Issue by Backtix** [kismetwireless/kismet#434]
Just noticed that the official site (https://www.kismetwireless.net/docs/readme/packages/) still uses the deprecated **apt-key**.
Thought I should mention it.

```
$ wget -O - https://www.kismetwireless.net/repos/kismet-release.gpg.key | sudo apt-key add -
(...)
```

**Comment by solsticedhiver** [comment]
So instead the following command would be recommended:

1. First download the key and store it under `/usr/share/keyrings`

        wget -O- https://www.kismetwireless.net/repos/kismet-release.gpg.key|gpg --dearmor | sudo tee /usr/share/keyrings/kismet-archive-keyring.gpg

2. Then add the repo while refering to the key previously downloaded:

         echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/kismet-archive-keyring.gpg] https://www.kismetwireless.net/repos/apt/release/jammy jammy main' | sudo tee /etc/apt/sources.list.d/kismet.list

    This is an example for ubuntu 22.04 amd64, so the previous line has to be changed given the distro
