### ISSUE TITLE
RTL433 Shrader TPMS data diplayed incomplete

### ISSUE THREAD

**Issue by Francklin2** [kismetwireless/kismet#44]
Hello
I notice the TPMS from Shrader only display the temperature, on the rtl_433 software it also give the tire pressure, perhaps only the first line of data is displayed (there aslso could be more data on the Interlogix sensor reading)
Thanks for your awesome work !!

**Comment by kismetwireless** [comment]
RTL433 currently has no explicit TPMS support; that is still under development; what you're seeing is it matching one field and taking it's best guess.

In the future there will be explicit tpms support; it's on the short list.
