### ISSUE TITLE
how to convert from unified .kismet logs to .pcap ?

### ISSUE THREAD

**Issue by saveyour** [kismetwireless/kismet#54]
i'm using the latest version compiled from git

i updated my kismet_log.conf to have log_type=pcap but i have a bunch of older unified log files with data i'd like to extract

they appear to be sqlite3.x db type files

 my question is how do i extract the .pcap data from these unified log type .kismet files?

thanks

**Comment by kismetwireless** [comment]
Tools are in the log_tools/ directory
