### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by shutdowng0** [kismetwireless/kismet#57]
git clone 5 days before compiled fine on a debian stretch
4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

Today a git clone, configure, make on the same systeme stops with:

In file included from packet.h:39:0,
                 from util.cc:66:
trackedelement.h:217:27: error: enclosing class of constexpr non-static member function `TrackerType TrackerElement::get_type() const' is not a literal type
     constexpr TrackerType get_type() const {
                           ^~~~~~~~
trackedelement.h:167:7: note: `TrackerElement' is not literal because:
 class TrackerElement {
       ^~~~~~~~~~~~~~
trackedelement.h:167:7: note:   `TrackerElement' has a non-trivial destructor
g++ -Wall -g -I. -g -O2 -pthread -fopenmp  -c pollabletracker.cc -o pollabletracker.cc.o

**Comment by kismetwireless** [comment]
Should be fixed in the recent refactor; I'd suggest updating to a more modern gcc or clang at some point however because sooner or later it won't be possible to support the very old gcc interpretation of c++11 anymore.
