### ISSUE TITLE
Option --enable-capture-tools-only breaks build process

### ISSUE THREAD

**Issue by techge** [kismetwireless/kismet#58]
When using the option --enable-capture-tools-only the build stops and configure claims that libnl and libnm are'nt installed although they are.

```
./configure --enable-capture-tools-only

...
   OSX/Darwin capture : n/a (only OSX/Darwin)
         Linux Netlink: no (will not be able to make mac80211 vaps)
  Linux NetworkManager: no (will not be able to control NetworkManager) 
       Linux Bluetooth: yes
...
```

when building on the same system without the option --enable-capture-tools-only it works as aspected and the libraries are detected correctly. This was done on Debian stretch. No idea if this does matter...

**Comment by kismetwireless** [comment]
Should be fixed in recent commits
