### ISSUE TITLE
Too many devices (slow)

### ISSUE THREAD

**Issue by marcotuna** [kismetwireless/kismet#60]
Hello, I have about 28.950 entries however it is very unresponsive. I cannot use filter because it does not work at all with this many records. Is there any way I can limit Kismet devices?
I have --device-timeout=86400 (24h) on my kismet launch. I belive it is to clear devices with more than 24h, but it does not seem to be working.

**Comment by kismetwireless** [comment]
Once you get over 10,000 devices you'll need a fairly powerful system to do runtime sorting and filtering, yes; however with the latest code, you should see acceptable performance over 100,000 devices on most intel systems (provided you have 4 to 8 gig of ram), and tolerable performance on smaller embedded systems up to about 50,000 devices, again, depending on RAM.

If your system is going into swap, that's going to absolutely tank kismet.

--device-timeout is not a command line option, it's found in kismet_memory.conf or can be put in /usr/local/etc/kismet_site.conf as an override parameter; check the readme for how the site override works.
