### ISSUE TITLE
Kismet crashes when configured to run GPSD

### ISSUE THREAD

**Issue by informalsecurity** [kismetwireless/kismet#66]
When compiled from source and with the config file set to use gpsd - kismet server crashes on launch.

Line 46 in file gpsgpsd2.cc appears to have a mis-spelled variable that causes the issue:

TTIMETRACKER 

should be 

TIMETRACKER

affected line:

(-) auto timetracker = Globalreg::FetchMandatoryGlobalAs<Timetracker>("TTIMETRACKER");

(+) auto timetracker = Globalreg::FetchMandatoryGlobalAs<Timetracker>("TIMETRACKER");

**Comment by kismetwireless** [comment]
Absolutely right, good catch, thank you!  Should be fixed in the latest push.
