### ISSUE TITLE
Debug - IE tags corrupt

### ISSUE THREAD

**Issue by Ekitji** [kismetwireless/kismet#68]
Hi all! 

Have been banging my heads to solve this. Tried every possible solutions without success.

Starting kismet in Terminal with kismet - c wlan1 and I get the APs with Mac adresses but also several lines with:

Debug - IE tags corrupt 

Im believing it got to do with manuf, because i cant see any manufacturer. Only SSID for APs. but what i can see in kismet.conf and source path to manuf seems right. Whats causing this and any ideas for fixing it?

Running rasp pi 3 with kali Linux with awus036ac.

**Comment by kismetwireless** [comment]
IE tags corrupt means you're getting malformed packets - most likely they're garbage packets from nexmon, but i'd need to see a pcap to know more.

You won't get manuf info unless you install a manufacturer file - by default kismet will look for the one provided with wireshark, so if you install that (or likely just tshark though I'm not sure) you'll get manuf names; the file is relatively large so every tool installing it seems a little wasteful.
