### ISSUE TITLE
unknown type - 0 14

### ISSUE THREAD

**Issue by dreadnought** [kismetwireless/kismet#69]
There is a place where I see `debug - unknown type - 0 14` messages in the log every second, which come from the file `phy_80211_dissectors.cc`. The subtype 14 is already defined as `packet_sub_action_noack` and could be handled similar to subtype 13 like this: 

```diff
diff --git a/phy_80211_dissectors.cc b/phy_80211_dissectors.cc
index ac069eb..4aae93a 100644
--- a/phy_80211_dissectors.cc
+++ b/phy_80211_dissectors.cc
@@ -678,6 +678,12 @@ int Kis_80211_Phy::PacketDot11dissector(kis_packet *in_pack) {
             packinfo->dest_mac = mac_addr(addr0, PHY80211_MAC_LEN);
             packinfo->source_mac = mac_addr(addr1, PHY80211_MAC_LEN);
             packinfo->bssid_mac = mac_addr(addr3, PHY80211_MAC_LEN);
+        } else if (fc->subtype == packet_sub_action_noack) {
+            packinfo->subtype = packet_sub_action_noack;
+            fprintf(stderr, "no-ack - %u %u\n", fc->type, fc->subtype);
+            packinfo->dest_mac = mac_addr(addr0, PHY80211_MAC_LEN);
+            packinfo->source_mac = mac_addr(addr1, PHY80211_MAC_LEN);
+            packinfo->bssid_mac = mac_addr(addr3, PHY80211_MAC_LEN);
         } else {
             fprintf(stderr, "debug - unknown type - %u %u\n", fc->type, fc->subtype);
             packinfo->subtype = packet_sub_unknown;
```

But as I don't know what I am doing there and where else it needs to be handled, I am leaving this bug report.

**Comment by kismetwireless** [comment]
Seems reasonable; added in a recent commit!

To fully handle it there would need to be a categorizer in the phy_80211.cc area too, but since it's a super-short action frame, kismet actually doesn't usually use them - they tend to cause more problems than they're worth because they seem to get a lot of broken/invalid packets on many drivers.
