### ISSUE TITLE
Converting to Pcap

### ISSUE THREAD

**Issue by kbeflo** [kismetwireless/kismet#82]
On de427e3b2edafd1c65ef04cc9603122e391d7238, trying to convert *.kismet file into *.pcap using on kismet/log_tools 

`./kismet_log_to_pcap.py --in foo.kismet --outtitle foo --limit-packets 1000`

It still requires me to enter `--out foo` option. After adding that option it writes output into `foo` without breaking the capture into multiple files.

**Comment by kismetwireless** [comment]
Should be fixed in the latest commits
