### ISSUE TITLE
Package requirements (protobuf) were not met:

### ISSUE THREAD

**Issue by bitterzick** [kismetwireless/kismet#87]
Can anyone help me with this error after ./configure of kismet
------------------
configure: error: Package requirements (protobuf) were not met:

No package 'protobuf' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables protobuf_CFLAGS
and protobuf_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
-----------------------

thank you :)

**Comment by kismetwireless** [comment]
You don't say what distribution you're on or what packages you've installed
- knowing that would help.

You need whatever your distribution calls protocobuf, profobuf-c,
protobuf-compiler, and protobuf-c-compiler installed.  The list of packages
for ubuntu and ubuntu-like distributions (debian, kali, mint, etc) is in
the readme; for other distributions you'll have to figure out what your
distro calls those packages (and the other dependencies listed in the
readme).
