### ISSUE TITLE
Submitting .kismet files to Wigle.net

### ISSUE THREAD

**Issue by kbeflo** [kismetwireless/kismet#94]
Using a G-STAR IV GPS and Ralink RT5370's on a Raspberry Pi 3 running Raspbian with gpsd, I tried submitting a couple of .kismet files to Wigle.net. The files are processed but no New WiFi and GPS locations found. 

On the Kismet web interface GPS is green and GPS fixed with coordinates while running.

**Comment by kismetwireless** [comment]
I don't believe wigle has processing for the kismetdb format currently; now that the file format is getting nailed down, I'll talk to them about the possibility of adding it on their end.

In the meantime you could try to convert it to kml or some other format wigle accepts.

**Comment by kbeflo** [comment]
@kismetwireless I've tried every log format, none got accepted. Going to use Kismet 2016-07-R1 for now.

**Comment by designer2k2** [comment]
use the kismetdb_to_wiglecsv tool installed with latest kismet to convert the .kismet file to csv that works with wigle.
